spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1998yang
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80

mybatis-plus:
  mapper-locations: classpath:com/yangweiye/springbootdemos/*Mapper.xml
  type-aliases-package: com.yangweiye.springbootdemos.entity
  type-handlers-package: com.yangweiye.springbootdemos.TypeHandler
  configuration:
    map-underscore-to-camel-case: true
