spring:
  datasource:
    url: jdbc:mysql://152.136.145.182:3306/myblog
    username: yangweiye_admin
    password: 1998yang
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver